[toolchain]
configure_args = --disable-shared --enable-static --prefix=/ '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' --enable-soname-versions=yes --enable-pie=no
make_args = 
autoreconf_args = --force --install

